### ISSUE TITLE
riscv-mini doesn't support print and declare the float data type variable

### ISSUE THREAD

**Issue by jtxiao82** [ucb-bar/riscv-mini#14]
Hi,

I try to use the test.ld, syscall.c and crt.S from ([riscv-tools](https://github.com/riscv/riscv-tools.git) and checkout to **4635ab67966c763a84f7217bc2c20b65dcabc7ec**. Those sources exist in [riscv-tests/benchmarks/common/](https://github.com/riscv/riscv-tests/tree/c9022d2f63f50388b2ab1192966f30dbe7819a59/benchmarks/common). These two steps follow [riscv-mini/build-riscv-tools.sh](https://github.com/ucb-bar/riscv-mini/tree/master/custom-bmark)) for building the [custom-bmark](https://github.com/ucb-bar/riscv-mini/tree/master/custom-bmark).

It would be success for compiling program and execute simulation with no any warning like (**TOHOST: XXXX**).

The simulation warning will occur during execution the system call (like printf) or floating variable computation. The screenshot shows the warning during the previous two scenarios.

**main.c**
```c
int add(int a, int b);

int main(int argc, char** argv) {
  int res = add(3, 2);

  // Simple float variable computation
  float a = 1.0;
  for(int i = 0; i < 10; i++) {
    a += 0.5;
  }

  return res == 5 ? 0 : -1;
}

```
![image](https://user-images.githubusercontent.com/30294203/44037280-877258f6-9f46-11e8-8c6a-9d7933aee619.png)

Environment
- Ubuntu 16.04
- riscv-gnu-toolchain installtion (based on riscv-mini/build-riscv-tools.sh)
   - riscv32-unknown-elf-gcc (GCC) 5.3.0
- Verilator 3.922 2018-03-17

There is an another question. Could riscv-mini team provide the some source code ([riscv-mini/src/test/resources/](https://github.com/ucb-bar/riscv-mini/tree/master/src/test/resources)) and its corresponding crt.S, syscall.c, util.h, linker sciprt (test.ld).

Thanks you very much!!

**Comment by dhxsy1994** [comment]
Riscv-mini just support the basic RV32I ISA, so that float type will report error.
