### ISSUE TITLE
Error in make command

### ISSUE THREAD

**Issue by sagarbaba** [ucb-bar/riscv-mini#16]
I tried to follow the steps as given in the RAEADME. But the 'make' command gives an error as below:
```
sagar@LAPTOP-LRFVFPQJ:~/riscv-mini$ make
sbt -ivy /home/sagar/riscv-mini/.ivy2 "run /home/sagar/riscv-mini/generated-src"
/bin/sh: 1: sbt: not found
Makefile:17: recipe for target '/home/sagar/riscv-mini/generated-src/Tile.v' failed
make: *** [/home/sagar/riscv-mini/generated-src/Tile.v] Error 127
sagar@LAPTOP-LRFVFPQJ:~/riscv-mini$
```

I'm not sure why this happened.Do help.

**Comment by jackkoenig** [comment]
`/bin/sh: 1: sbt: not found`

You need to install `sbt`: https://www.scala-sbt.org/1.0/docs/Setup.html

**Comment by sagarbaba** [comment]
Thanks @jackkoenig .It worked. Now the 'make verilator' shows error:

sagar@Geek:~/riscv-mini$ make verilator
verilator --cc --exe --assert -Wno-STMTDLY -O3 --trace --top-module Tile -Mdir /home/sagar/riscv-mini/generated-src/VTile.csrc -CFLAGS "-std=c++11 -Wall -Wno-unused-variable -include /home/sagar/riscv-mini/generated-src/VTile.csrc/VTile.h"  -o /home/sagar/riscv-mini/VTile /home/sagar/riscv-mini/generated-src/Tile.v /home/sagar/riscv-mini/src/main/cc/top.cc /home/sagar/riscv-mini/src/main/cc/mm.cc
/bin/sh: 1: verilator: not found
Makefile:28: recipe for target '/home/sagar/riscv-mini/VTile' failed
make: *** [/home/sagar/riscv-mini/VTile] Error 127

Do help.

**Comment by edwardcwang** [comment]
`/bin/sh: 1: verilator: not found` implies that verilator needs to be installed, which one can do so through the package manager.

**Comment by sagarbaba** [comment]
Done,works. After the "$ ./VTile <hex file>" command, I'm supposed to get the waveform or just the execution trace in the command prompt?
Also can the .vcd file be used to view the waveform, if so what's the command for the same.
