### ISSUE TITLE
Building priv-1.7 riscv-toolchain fails

### ISSUE THREAD

**Issue by noureddine-as** [ucb-bar/riscv-mini#19]
Hello.

I made sure everything is set-up. The VTile.v is generated, I also got the .HEX pre-compiled tests working. now I want to create some additional software benchmarks. So I tried to build the priv-1.7 toolchain. The build process fails here:

```bash
In file included from /home/[.....]/riscv-mini/riscv-tools-priv1.7/riscv-gnu-toolchain/build/src/newlib-gcc/gcc/cp/except.c:1023:0:
cfns.gperf: In function ‘const char* libc_name_p(const char*, unsigned int)’:
cfns.gperf:101:1: error: ‘const char* libc_name_p(const char*, unsigned int)’ redeclared inline with ‘gnu_inline’ attribute
cfns.gperf:26:14: note: ‘const char* libc_name_p(const char*, unsigned int)’ previously declared here
cfns.gperf: At global scope:
cfns.gperf:26:14: warning: inline function ‘const char* libc_name_p(const char*, unsigned int)’ used but never defined
make[3]: *** [cp/except.o] Error 1
make[2]: *** [all-gcc] Error 2
make[1]: *** [all] Error 2
make: *** [stamps/build-gcc-newlib] Error 2
```

Is there any other working commit ID of `riscv-tools` that support priv-1.7 and compiles successfully?

**Comment by chiehlim** [comment]
I have the same issue. have you found a solution?

**Comment by noureddine-as** [comment]
@chiehlim  No, unfortunately I didn't.

**Comment by HenrySearch** [comment]
i meet the same problem and change gcc to version 5.5.0, and the problem is solved .
