### ISSUE TITLE
Proposal to Update Project to Latest Chisel

### ISSUE THREAD

**Issue by chick** [ucb-bar/riscv-mini#23]
I'd like to propose the following. 

1. Make the current master branch become the release branch
    - Make release be the default branch in this repo
    - It will, for now, continue to point to its desired version of chisel3
    - This would allow us to work on master, buffering existing users
1. After the above change master branch
    1. Point to current 3.2-SNAPSHOT
    1. Fix all code to be compliant and as warning free as possible with Chisel 3.2
    1. put all code in main and tests into a `mini` package
        - This will bring it in line with standard Scala conventions
1. Change master to depend on chisel-testers2 instead of chisel3
    - This would allow us to develop some testers2 style unit tests
        - This would help test out testers2 capabilities
        - Provide alternative examples of unit testing facilities under chisel

**Comment by chick** [comment]
@donggyukim Can you let me know what you think of this proposal.
I am prepared to do the described work and testing.
I am also interested in making sure Treadle can handle riscv-mini and this seems like a good path.

**Comment by donggyukim** [comment]
@chick I love this proposal. Can't wait to see tests running on Treadle! There used to be chisel-testers1.0-based tests, and I hope it'll be helpful for porting:
https://github.com/ucb-bar/riscv-mini/tree/6b889ec7ba5d72876f764532220725d49c49b912/src/test/scala

**Comment by chick** [comment]
@donggyukim Thanks
As a first step I have created a `release` branch. The only change from master was removing
the "-SNAPSHOT" from the version string in `build.sbt`.
If this is ok with you I think the next steps should be 

1. Make `release` be the default branch
1. Make a release tag for `release`
1. Add protection rules to the `release` and `master` branches to require PRs
    - I think this is optional but protects against accidental changes.

Does this sound ok? If so, I am happy to do them.
