### ISSUE TITLE
Running simulation with other programs?

### ISSUE THREAD

**Issue by hauhsu** [ucb-bar/riscv-mini#3]
I saw that the provided tests run the existing hex files.
How can I run my own programs on this platform?
I tried to compile and transfer the **vvadd** program in **riscv-tests** to hex file, 
then replace the **vvadd.riscv.hex** in src/test/resources.
But the test fails: 

> CoreTests.scala:61 assert(cycle < maxcycles.U)

Can you provide complete building steps?
Thanks!

**Comment by donggyukim** [comment]
We should use a very old version of riscv-tools. Let me add the tool hash in the repo.
