### ISSUE TITLE
after I use quartus II 9.0 to compile Title.v successfully, but I double click ALUArea::alu module turn on error below attached

### ISSUE THREAD

**Issue by zhouxs1023** [ucb-bar/riscv-mini#4]
after I use quartus II 9.0 to compile Title.v successfully, but I double click ALUArea::alu module turn on error as below:
![360-16581118485047](https://user-images.githubusercontent.com/905931/31616622-c3999cbe-b2bf-11e7-8fca-456ab039a58e.png)
if alu module have a bug ??

**Comment by donggyukim** [comment]
It was fine with Vivado. `ALUArea` may not be friendly to FPGA since it's optimized for ASIC. Can you try `ALUSimple` instead?
https://github.com/ucb-bar/riscv-mini/blob/master/src/main/scala/Config.scala#L13
