### ISSUE TITLE
Is this a BUG in TileTester.scala?

### ISSUE THREAD

**Issue by LingZichao** [ucb-bar/riscv-mini#52]
https://github.com/ucb-bar/riscv-mini/blob/d3bfaf99bbd778028e92b402cbf55035f07230ff/src/test/scala/mini/TileTester.scala#L88

In my view,`aw` shall be `ar` , which stands for read address channel in AXI

**Comment by ekiwi** [comment]
Could be. What happens if you change it?

**Comment by LingZichao** [comment]
Uhhh ... Because there is no out-of-order transaction , so it just maybe a ctrl c+v bug and no negative impact.   : )

**Comment by ekiwi** [comment]
> Uhhh ... Because there is no out-of-order transaction , so it just maybe a ctrl c+v bug and no negative impact. : )

feel free to still make a PR. Seems like something that should be fixed

**Comment by LingZichao** [comment]
#53
