### ISSUE TITLE
instruction doesn't appear in spec? 

### ISSUE THREAD

**Issue by sequencer** [ucb-bar/riscv-mini#9]
Hello, Kim, I have a question that [FENCEI](https://github.com/ucb-bar/riscv-mini/blob/e2c20f494238381c25842c29fbaaccbd757b2e5c/src/main/scala/Instructions.scala#L56) doesn't appear in the [riscv-isa-manual](https://github.com/riscv/riscv-isa-manual), did I miss some thing?

**Comment by donggyukim** [comment]
FENCE.I is mentioned in Section 2.7:
https://riscv.org/specifications/

**Comment by sequencer** [comment]
Thank you, I got it!
